version: 2
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: apt-get update -qq && apt-get install -qq git
      - checkout
      - run: DEBIAN_FRONTEND=noninteractive ./InstallPackagesUbuntu.sh
      - run: make
  build-ubuntu-2204:
    docker:
      - image: ubuntu:22.04
    steps:
      - run: apt-get update -qq && apt-get install -qq git
      - checkout
      - run: DEBIAN_FRONTEND=noninteractive ./InstallPackagesUbuntu.sh
      - run: make
  build-v4l:
    docker:
        - image: ubuntu:20.04
    steps:
      - run: apt-get update -qq && apt-get install -qq git
      - checkout
      - run: DEBIAN_FRONTEND=noninteractive ./InstallPackagesUbuntu.sh
      - run: mkdir -p build
      - run: cmake -B build -DUSE_V4L=true .
      - run: make
  build-splitter:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: apt-get update -qq && apt-get install -qq git
      - checkout
      - run: DEBIAN_FRONTEND=noninteractive ./InstallPackagesUbuntu.sh
      - run: mkdir -p build
      - run: cmake -B build -DUSE_SPLITTER=true .
      - run: make

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build-ubuntu-2204
      - build-v4l
      - build-splitter
